"""
embed_cjk_font.py - PlatformIO pre-build extra script

Generates a RISC-V assembly file (src/pretendard_embed.S) that uses
.incbin to embed all Pretendard epdfont sizes (12, 14, 16pt) into .rodata
(Flash). Zero-copy: no RAM allocation for font data.
"""

import os
Import("env")  # type: ignore  # noqa: F821  (PlatformIO SCons global)

PROJECT_DIR = env["PROJECT_DIR"]
ASM_OUT = os.path.join(PROJECT_DIR, "src", "pretendard_embed.S")

SIZES = [12, 14, 16]

lines = ["/* Auto-generated by scripts/embed_cjk_font.py — do not edit */"]
for sz in SIZES:
    font_src = os.path.join(
        PROJECT_DIR, "lib", "EpdFont", "builtinFonts", f"pretendard_{sz}.epdfont"
    ).replace(os.sep, '/')
    sym = f"_binary_pretendard_{sz}_epdfont"
    lines.append(f"""    .section .rodata
    .balign 4
    .global {sym}_start
{sym}_start:
    .incbin "{font_src}"
{sym}_end:
    .global {sym}_end
""")

asm_content = "\n".join(lines) + "\n"

existing = ""
if os.path.exists(ASM_OUT):
    with open(ASM_OUT, "r", encoding="utf-8") as f:
        existing = f.read()

if existing != asm_content:
    with open(ASM_OUT, "w", encoding="utf-8") as f:
        f.write(asm_content)
    print(f"[embed_cjk_font] Generated {ASM_OUT} ({len(SIZES)} sizes)")
else:
    print(f"[embed_cjk_font] {ASM_OUT} is up-to-date")
