"""
embed_cjk_font.py - PlatformIO pre-build extra script

Generates a RISC-V assembly file (src/pretendard_12_embed.S) that uses
.incbin with the absolute path to the epdfont binary.  This ensures the font
is placed in .rodata (Flash) with the exact linker-symbol names expected by
main.cpp and SdFont.
"""

import os
Import("env")  # type: ignore  # noqa: F821  (PlatformIO SCons global)

PROJECT_DIR = env["PROJECT_DIR"]
FONT_SRC = os.path.join(
    PROJECT_DIR,
    "lib", "EpdFont", "builtinFonts", "pretendard_12.epdfont"
)
ASM_OUT = os.path.join(PROJECT_DIR, "src", "pretendard_12_embed.S")

SYMBOL = "_binary_pretendard_12_epdfont"

asm_content = f"""\
/* Auto-generated by scripts/embed_cjk_font.py — do not edit */
    .section .rodata
    .balign 4
    .global {SYMBOL}_start
{SYMBOL}_start:
    .incbin "{FONT_SRC.replace(os.sep, '/')}"
{SYMBOL}_end:
    .global {SYMBOL}_end
"""

# Only regenerate if content changed (avoids unnecessary recompiles)
existing = ""
if os.path.exists(ASM_OUT):
    with open(ASM_OUT, "r") as f:
        existing = f.read()

if existing != asm_content:
    with open(ASM_OUT, "w") as f:
        f.write(asm_content)
    print(f"[embed_cjk_font] Generated {ASM_OUT}")
else:
    print(f"[embed_cjk_font] {ASM_OUT} is up-to-date")
